name: Daily Run

on:
  schedule:
    - cron: '20 9 * * *'  # Runs daily at 9:20 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'  # Specify your Go version here

      - name: Run Go Script
        run: go run main.go

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update data" --allow-empty
          git push
